### ISSUE TITLE
Unrecognized client exception when calling the GetTableMetadata operation: The security token included in the request is invalid.

### ISSUE THREAD

**Issue by NatalieLow** [NREL/buildstock-query#46]
Issue overview
--------------

 When attempting to use the buildstock-query notebooks, I'm getting a Client / Operational Error. 

## Steps to Reproduce

1.
`from buildstock_query import BuildStockQuery`
(works fine)
2.
aws configuration
(enter keys, region, etc.)
Account has: 
- AdministratorAccess
- AmazonAthenaFullAccess
- AmazonS3FullAccess

3.
`my_run = BuildStockQuery(workgroup='rescore',
  db_name='euss-final',
   table_name='euss_res_final_2018_550k_20220901')`
This and[ various other ](https://github.com/NREL/buildstock-query/blob/main/example_usage/basic_usage_oedi.ipynb)table names and working groups produce Client / Operational errors:
OperationalError: An error occurred (UnrecognizedClientException) when calling the GetTableMetadata operation: The security token included in the request is invalid.
<img width="631" alt="Screenshot 2024-05-10 at 11 54 14 AM" src="https://github.com/NREL/buildstock-query/assets/5697015/8ca9ac36-24e3-40bc-956a-df6d426f840e">
<img width="829" alt="Screenshot 2024-05-10 at 11 55 18 AM" src="https://github.com/NREL/buildstock-query/assets/5697015/3b845eed-d0e9-47ba-8981-05929640f865">
<img width="791" alt="Screenshot 2024-05-10 at 11 56 00 AM" src="https://github.com/NREL/buildstock-query/assets/5697015/a0151379-b4de-4dfc-991b-ce1e81da2817">

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): MacOS Sonoma 14.4.1, Apple M2
 - Version of OpenStudio (if using an intermediate build, include SHA): OS: 3.7.0, 3.6.1, 3.5.1, 3.4.0
 - Python versions attempted: 3.10.13, 3.12.0

### Context

We're able to query and access the Data Lake via AWS Athena interface, but would also like to use the python querying tools to more easily interface with our analysis of residential data.

**Comment by rajeee** [comment]
Are you sure you have access to that particular database and table in Athena with your user account?

**Comment by NatalieLow** [comment]
Hi! 

With this user account I am able to use AWS glue and set up a crawler to create tables from the oedi data lake, then run queries in Athena. I'm assuming this means I have access?

**Comment by rajeee** [comment]
You should be able to go to Athena console and see those specific db and table name. If you can't, then you will need to first create those. Please follow the instructions here: https://www.youtube.com/watch?v=qSR1MFpSiro&t=0s

**Comment by NatalieLow** [comment]
I still seem to be missing something. 

In Athena, everything seems to work well.

I have two tables: one for the metadata and one for the time series data. 

I've also tried specifying the db_schema = resstock_oedi as it maps to my table suffixes.

Do you have any other ideas?

Thank you!

<img width="751" alt="Screenshot 2024-07-15 at 3 37 41 PM" src="https://github.com/user-attachments/assets/6c6ff30b-9eee-4dde-91fd-2be2d5cd2cf0">
<img width="1383" alt="Screenshot 2024-07-15 at 3 29 19 PM" src="https://github.com/user-attachments/assets/e6036ba2-2db1-41d0-a4ac-b3d94f653bc8">

**Comment by rajeee** [comment]
Thanks for the screenshot. That's very helpful.

It seems like somehow the credentials being pulled is not granting you the required permission.
Could you maybe try by adding this in the begining.
```
import os
os.environ['AWS_ACCESS_KEY_ID'] = '<access_key>' 
os.environ['AWS_SECRET_ACCESS_KEY']  = '<secret_key>'
```

**Comment by NatalieLow** [comment]
It worked. Thank you!  

I needed a couple of additional steps: 

1) Added my session token in addition to the key ID and access key:
os.environ['AWS_SESSION_TOKEN']  = '`<session token`>'


2) Specified a location for the query results in the workgroup 
<img width="470" alt="Screenshot 2024-07-16 at 10 28 14 AM" src="https://github.com/user-attachments/assets/e8f86e7a-92e2-46b3-920e-9796dcaa2314">

<img width="1218" alt="Screenshot 2024-07-16 at 10 31 18 AM" src="https://github.com/user-attachments/assets/228f7a81-8eb9-4b93-a7aa-2cfaf0585ef3">
